### ISSUE TITLE
Unexpected Keyword Argument 'authorization_token'

### ISSUE THREAD

**Issue by teshiburu2017** [pnbruckner/life360#1]
Hey!

Just taking a look at this and it seems it could do what i want. However, when i try to run your example I'm getting the below error 

```
Traceback (most recent call last):
  File "life360_test.py", line 38, in <module>
    api = life360(authorization_token=authorization_token, username=username, password=password)
TypeError: __init__() got an unexpected keyword argument 'authorization_token'
```
Any ideas?

**Comment by pnbruckner** [comment]
Hi, sorry, I just noticed the issue you logged. This repo is a work in progress. I originally started with the code from the repo I forked this from to be used with a custom device_tracker component I created for Home Assistant. All the work for that is in a different repo. Now I'm in the process of moving that work back here so that I can publish it on PyPI. The intention of the work in this repo is strictly to support the other work I'm doing for Home Assistant. If you'd rather use this in a different way, then you should probably create your own fork from this repo's parent fork (or just use the parent fork.) I don't intend (at least not at first) to support other use cases.

**Comment by pnbruckner** [comment]
@teshiburu2017, I think I've got this into a reasonable state now, and although I don't really document how to use it outside of Home Assistant, it should certainly be usable elsewhere. You can take a look at my Home Assistant [custom device tracker platform code](https://github.com/pnbruckner/homeassistant-config/blob/master/custom_components/life360/device_tracker.py) for an idea of how to use it. If you'd still like to try using it, and if you run into any problems, I can try to help.
