### ISSUE TITLE
Is the Life360 API Still Closed?

### ISSUE THREAD

**Issue by Nicolas-Gatien** [pnbruckner/life360#19]
Hey! I checked the closed issues and I saw one from Jan 3rd saying the API was closed.
I this still the case?

I was playing around with this library and whether I log in with the token or with my credentials, I get stopped when I try to fetch an endpoint and receive a 403 error.

**Comment by pnbruckner** [comment]
What version of this custom integration are you using? Also, what version of HA are you using?

**Comment by Nicolas-Gatien** [comment]
life360==7.0.1

I'm not using Home Assistants, I'm just trying to communicate with the life360 api.

What I'm doing is the following:

I initialize an API without an authorization:
```python
api = Life360(
            session=session,
            max_retries=3,
            name="MyLife360App"
        )
```

The session is a `aiohttp.ClientSession`

Then I log in with my details:
```python
authorization = await api.login_by_username(
                username="MY-EMAIL",
                password="MY-PASSWORD"
            )
```

**Comment by pnbruckner** [comment]
Oh, sorry, I now see this issue is on the life360 package, not the ha-life360 HA custom integration. Oops!

The Life360 server is much less forgiving these days, and it's not uncommon to see a lot of errors resulting in a lot of retries on certain aspects. If you want an idea what hoops you'll have to jump through, take a look at my ha-life360 repository (which is the HA custom integration.)

As it says in the readme, this package is only intended to support the HA integration. Although you may be able to get it to work on its own, I don't really support that use case.

**Comment by Nicolas-Gatien** [comment]
Great, I'll take a look -- thank you :D

**Comment by ryanbuckner** [comment]
> Great, I'll take a look -- thank you :D

Did you get this working? I'd like to revive my broken Indigo [Domotics plugin for Life360](https://github.com/ryanbuckner/life360-plugin)

**Comment by Nicolas-Gatien** [comment]
@ryanbuckner, not yet, I'm still trying to establish a connection, I'll ping you in this issue if I get it working.

**Comment by ryanbuckner** [comment]
> @ryanbuckner, not yet, I'm still trying to establish a connection, I'll ping you in this issue if I get it working.

Thanks!
